### ISSUE TITLE
Conda install not working

### ISSUE THREAD

**Issue by plurb** [petrikvladimir/pyphysx#63]
PS C:\Users\shurj\PycharmProjects\MinecraftClone> pip install git+https://github.com/petrikvladimir/pyphysx.git@master
Collecting git+https://github.com/petrikvladimir/pyphysx.git@master
  Cloning https://github.com/petrikvladimir/pyphysx.git (to revision master) to c:\users\shurj\appdata\local\temp\pip-req-build-q0bk4z91
  Running command git clone -q https://github.com/petrikvladimir/pyphysx.git 'C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91'
  Resolved https://github.com/petrikvladimir/pyphysx.git to commit d389e3e12e198b1f8aefd40dd3910af01e3b1944
Collecting conan
  Using cached conan-1.46.2-py3-none-any.whl
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\minecraftclone\lib\site-packages (from pyphysx==0.2.1) (1.21.5)
Collecting imageio
  Using cached imageio-2.16.1-py3-none-any.whl (3.3 MB)
Collecting imageio_ffmpeg
  Using cached imageio_ffmpeg-0.4.5-py3-none-win_amd64.whl (22.6 MB)
Collecting trimesh
  Using cached trimesh-3.10.7-py3-none-any.whl (642 kB)
Collecting networkx
  Using cached networkx-2.7.1-py3-none-any.whl (2.0 MB)
Collecting numba
  Using cached numba-0.55.1-cp38-cp38-win_amd64.whl (2.4 MB)
Collecting numpy_quaternion
  Using cached numpy_quaternion-2022.2.10.14.20.39-cp38-cp38-win_amd64.whl (62 kB)
Collecting matplotlib
  Using cached matplotlib-3.5.1-cp38-cp38-win_amd64.whl (7.2 MB)
Collecting scipy
  Using cached scipy-1.8.0-cp38-cp38-win_amd64.whl (36.9 MB)
Collecting anytree
  Using cached anytree-2.8.0-py2.py3-none-any.whl (41 kB)
Collecting pyrender
  Using cached pyrender-0.1.45-py3-none-any.whl (1.2 MB)
Collecting meshcat
  Using cached meshcat-0.3.2-py3-none-any.whl (2.6 MB)
Collecting pycollada
  Using cached pycollada-0.7.2-py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in c:\programdata\anaconda3\envs\minecraftclone\lib\site-packages (from anytree->pyphysx==0.2.1) (1.16.0)
Collecting urllib3<1.27,>=1.26.6
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting patch-ng<1.18,>=1.17.4
  Using cached patch_ng-1.17.4-py3-none-any.whl
Collecting requests<3.0.0,>=2.25
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting pygments<3.0,>=2.0
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting colorama<0.5.0,>=0.3.3
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting node-semver==0.6.1
  Using cached node_semver-0.6.1-py3-none-any.whl (10 kB)
Collecting tqdm<5,>=4.28.1
  Using cached tqdm-4.63.1-py2.py3-none-any.whl (76 kB)
Collecting python-dateutil<3,>=2.7.0
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting Jinja2<4.0.0,>=3.0
  Using cached Jinja2-3.1.1-py3-none-any.whl (132 kB)
Collecting PyJWT<2.0.0,>=1.4.0
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting pluginbase>=0.5
  Using cached pluginbase-1.0.1-py3-none-any.whl
Collecting fasteners>=0.14.1
  Using cached fasteners-0.17.3-py3-none-any.whl (18 kB)
Collecting bottle<0.13,>=0.12.8
  Using cached bottle-0.12.19-py3-none-any.whl (89 kB)
Collecting PyYAML<6.0,>=3.11
  Using cached PyYAML-5.4.1-cp38-cp38-win_amd64.whl (213 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp38-cp38-win_amd64.whl (17 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\minecraftclone\lib\site-packages (from requests<3.0.0,>=2.25->conan->pyphysx==0.2.1) (2021.10.8)
Collecting pillow>=8.3.2
  Using cached Pillow-9.0.1-cp38-cp38-win_amd64.whl (3.2 MB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.2-cp38-cp38-win_amd64.whl (55 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.31.2-py3-none-any.whl (899 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting ipython>=5
  Using cached ipython-8.2.0-py3-none-any.whl (750 kB)
Collecting pyzmq>=17.0.0
  Using cached pyzmq-22.3.0-cp38-cp38-win_amd64.whl (1.0 MB)
Collecting tornado>=4.0.0
  Using cached tornado-6.1-cp38-cp38-win_amd64.whl (422 kB)
Collecting pyngrok>=4.1.6
  Using cached pyngrok-5.1.0-py3-none-any.whl
Collecting u-msgpack-python>=2.4.1
  Using cached u_msgpack_python-2.7.1-py2.py3-none-any.whl (10.0 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.16
  Using cached jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
Collecting traitlets>=5
  Using cached traitlets-5.1.1-py3-none-any.whl (102 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.28-py3-none-any.whl (380 kB)
Collecting stack-data
  Using cached stack_data-0.2.0-py3-none-any.whl (21 kB)
Collecting matplotlib-inline
  Using cached matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Requirement already satisfied: setuptools>=18.5 in c:\programdata\anaconda3\envs\minecraftclone\lib\site-packages (from ipython>=5->meshcat->pyphysx==0.2.1) (58.0.4)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.0-cp38-cp38-win_amd64.whl (23.2 MB)
Collecting freetype-py
  Using cached freetype_py-2.2.0-py3-none-win_amd64.whl (708 kB)
Collecting PyOpenGL==3.1.0
  Using cached PyOpenGL-3.1.0-py3-none-any.whl
Collecting pyglet>=1.4.10
  Using cached pyglet-1.5.23-py3-none-any.whl (1.1 MB)
Collecting executing
  Using cached executing-0.8.3-py2.py3-none-any.whl (16 kB)
Collecting asttokens
  Using cached asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Building wheels for collected packages: pyphysx
  Building wheel for pyphysx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\MinecraftClone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\setup.py'"'"
'; __file__='"'"'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\shurj\AppData\Local\Temp\pip-wheel-spd1m36b'     
       cwd: C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\
  Complete output (69 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\meshcat_render.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\pyrender.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\pyrender_base.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\pyrender_offscreen_renderer.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\pyrender_trackball.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\render_base.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\utils.py -> build\lib.win-amd64-3.8\pyphysx_render
  copying pyphysx_render\__init__.py -> build\lib.win-amd64-3.8\pyphysx_render
  creating build\lib.win-amd64-3.8\pyphysx_utils
  copying pyphysx_utils\rate.py -> build\lib.win-amd64-3.8\pyphysx_utils
  copying pyphysx_utils\transformations.py -> build\lib.win-amd64-3.8\pyphysx_utils
  copying pyphysx_utils\tree_robot.py -> build\lib.win-amd64-3.8\pyphysx_utils
  copying pyphysx_utils\urdf_robot_parser.py -> build\lib.win-amd64-3.8\pyphysx_utils
  copying pyphysx_utils\__init__.py -> build\lib.win-amd64-3.8\pyphysx_utils
  running build_ext
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/shurj/AppData/Local/Temp/pip-req-build-q0bk4z91/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\setup.py", line 68, in <module>
      setup(
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\setup.py", line 32, in run
      self.build_extension(ext)
    File "C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\setup.py", line 64, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91', '-DPHYSX_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91
\\build\\lib.win-amd64-3.8\\', '-DPYTHON_EXECUTABLE=C:\\ProgramData\\Anaconda3\\envs\\MinecraftClone\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\build\\lib.win-amd64-3.8\\', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pyphysx
  Running setup.py clean for pyphysx
Failed to build pyphysx
Installing collected packages: wcwidth, traitlets, pure-eval, parso, executing, asttokens, urllib3, stack-data, PyYAML, pyparsing, pygments, prompt-toolkit, pillow, pickleshare, matplotlib-inline, MarkupSafe, jedi,
 idna, decorator, colorama, charset-normalizer, backcall, u-msgpack-python, trimesh, tqdm, tornado, scipy, requests, pyzmq, python-dateutil, PyOpenGL, pyngrok, PyJWT, pyglet, pluginbase, patch-ng, packaging, node-s
emver, networkx, llvmlite, kiwisolver, Jinja2, ipython, imageio, freetype-py, fonttools, fasteners, cycler, bottle, pyrender, pycollada, numpy-quaternion, numba, meshcat, matplotlib, imageio-ffmpeg, conan, anytree, pyphysx
    Running setup.py install for pyphysx ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\MinecraftClone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\setup.py'"
'"'; __file__='"'"'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptoo
ls import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shurj\AppData\Local\Temp\pip-record-9pmsfiq4\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\MinecraftClone\Include\pyphysx'
         cwd: C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\
    Complete output (71 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\meshcat_render.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\pyrender.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\pyrender_base.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\pyrender_offscreen_renderer.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\pyrender_trackball.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\render_base.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\utils.py -> build\lib.win-amd64-3.8\pyphysx_render
    copying pyphysx_render\__init__.py -> build\lib.win-amd64-3.8\pyphysx_render
    creating build\lib.win-amd64-3.8\pyphysx_utils
    copying pyphysx_utils\rate.py -> build\lib.win-amd64-3.8\pyphysx_utils
    copying pyphysx_utils\transformations.py -> build\lib.win-amd64-3.8\pyphysx_utils
    copying pyphysx_utils\tree_robot.py -> build\lib.win-amd64-3.8\pyphysx_utils
    copying pyphysx_utils\urdf_robot_parser.py -> build\lib.win-amd64-3.8\pyphysx_utils
    copying pyphysx_utils\__init__.py -> build\lib.win-amd64-3.8\pyphysx_utils
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:2 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/shurj/AppData/Local/Temp/pip-req-build-q0bk4z91/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\setup.py", line 68, in <module>
        setup(
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\setup.py", line 32, in run
        self.build_extension(ext)
      File "C:\Users\shurj\AppData\Local\Temp\pip-req-build-q0bk4z91\setup.py", line 64, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\ProgramData\Anaconda3\envs\MinecraftClone\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91', '-DPHYSX_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z
91\\build\\lib.win-amd64-3.8\\', '-DPYTHON_EXECUTABLE=C:\\ProgramData\\Anaconda3\\envs\\MinecraftClone\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\build\\lib.win-amd64-3.8\\', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\MinecraftClone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shurj\\AppData\\Local\\Temp\\p
ip-req-build-q0bk4z91\\setup.py'"'"'; __file__='"'"'C:\\Users\\shurj\\AppData\\Local\\Temp\\pip-req-build-q0bk4z91\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) el
se io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shurj\AppDat
a\Local\Temp\pip-record-9pmsfiq4\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\MinecraftClone\Include\pyphysx' Check the logs for full command output.

**Comment by petrikvladimir** [comment]
Hi @plurb, I don't have enough experience with windows so I might not be able to help. Can you try a fix mentioned here: 
https://stackoverflow.com/questions/48624415/how-to-fix-cmake-error-in-cmakelists-txt-generator-nmake-makefiles-does-not-sup
i.e. `pip install dlib==19.4 ` ?
In addition, you can try to install cmake through conda, `conda install -c anaconda cmake`. 
Please, let me know if any of this helps.
