### ISSUE TITLE
Add support for GPU

### ISSUE THREAD

**Issue by petrikvladimir** [petrikvladimir/pyphysx#9]

**Comment by benalex99** [comment]
I am having issues with this. Trying your GPU test example gives me this notification:

C:\J\w\prod\BuildSingleReference@5\s\d5ef42\1\src\physx\source\simulationcontroller\src\ScScene.cpp (685) : warning : GPU solver pipeline failed, switching to software
C:\J\w\prod\BuildSingleReference@5\s\d5ef42\1\src\physx\source\simulationcontroller\src\ScScene.cpp (699) : warning : GPU Bp pipeline failed, switching to software

And the performance shows it indeed does not use the GPU. I am using an rtx3060 with latest drivers. Have tested this on windows and ubuntu with the same result.

Any troubleshoot?
